# `Bag of words using Naive Bayes`
- Uses Bayes theorem

#### [Deep Learning Krish naik playlist](https://www.youtube.com/playlist?list=PLZoTAELRMXVPGU70ZGsckrMdr0FteeRUi)
#### [Flutter](https://flutter.dev/)
#### [Sentiment Analysis](https://medium.com/@pyashpq56/sentiment-analysis-on-imdb-movie-review-d004f3e470bd#id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjMzZmY1YWYxMmQ3NjY2YzU4Zjk5NTZlNjVlNDZjOWMwMmVmOGU3NDIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJuYmYiOjE2NDI0MjEyODIsImF1ZCI6IjIxNjI5NjAzNTgzNC1rMWs2cWUwNjBzMnRwMmEyamFtNGxqZGNtczAwc3R0Zy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInN1YiI6IjExMzEwMjE1MTk0Mjg5ODY4NTI5OSIsImVtYWlsIjoibWFudWpqb3NoaTUyQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhenAiOiIyMTYyOTYwMzU4MzQtazFrNnFlMDYwczJ0cDJhMmphbTRsamRjbXMwMHN0dGcuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJuYW1lIjoiTWFudWogS3VtYXIgSm9zaGkiLCJwaWN0dXJlIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EtL0FPaDE0R2o0ejZwaE43bTd6OHVmVUppRE82MnVvUGlSZ1Jlb1RrQTFHSzZSU2c9czk2LWMiLCJnaXZlbl9uYW1lIjoiTWFudWogS3VtYXIiLCJmYW1pbHlfbmFtZSI6Ikpvc2hpIiwiaWF0IjoxNjQyNDIxNTgyLCJleHAiOjE2NDI0MjUxODIsImp0aSI6ImNlM2NkOGYxMmU3NWI1YjdlOGZhYjZkZDFjOGRmNjQ1NmFiOWY1OWYifQ.o5v4Lzx5HnBeI-GpVrlXvtD9_wapDF4JluQumyjvbCszzYXiu4ZNv99Fxi26OFihh6uC6zDn-1mxva6L5yhy98Yb1uMEVlm5p8XTX7ihMZppR4kOkLW_mCtwbGQ99_e4CfggY1DZyFYhQkJ6hayen99vJjeg4hbslKbqODEvTUPVDJMNy8Qy1CKU-sJoPODUs9ML4Tpp6oQbPdPaycmgppkm2bXxd57WKNARcbd2mBj5GomWdCm-mX5YCXVqci8woPLmBeZWd7zCKKIWyYwFb5Rv8HdTu3_PcBDaQ1WoizjyAYna1Wdacb8vLPXrs7RX9o8OdEKGQ_sct9UsHVF8RQ)

In [1]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.feature_extraction.text import CountVectorizer  # help us to count the tokens
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, f1_score, precision_score
from nltk.corpus import stopwords
import nltk
import re
import string
from nltk.stem import WordNetLemmatizer

In [2]:
phrases = ['I want to learn machine learning','I am working at innomatics','I am learning machine learning at innomatics']
vect = CountVectorizer()
vect.fit(phrases)

CountVectorizer()

In [3]:
print('vocab size = {}'.format(len(vect.vocabulary_)))

vocab size = 9


In [4]:
print('vocabulary =',vect.vocabulary_)

vocabulary = {'want': 7, 'to': 6, 'learn': 3, 'machine': 5, 'learning': 4, 'am': 0, 'working': 8, 'at': 1, 'innomatics': 2}


### it had just ordered the tokens 

In [5]:
bag_of_words = vect.transform(phrases)
print(bag_of_words)

  (0, 3)	1
  (0, 4)	1
  (0, 5)	1
  (0, 6)	1
  (0, 7)	1
  (1, 0)	1
  (1, 1)	1
  (1, 2)	1
  (1, 8)	1
  (2, 0)	1
  (2, 1)	1
  (2, 2)	1
  (2, 4)	2
  (2, 5)	1


### it is the frequency now
### there are some tokens which countvectorizer automatically removes, it is a kind of preprocessing, removes some stop words

In [6]:
print(bag_of_words.toarray())

[[0 0 0 1 1 1 1 1 0]
 [1 1 1 0 0 0 0 0 1]
 [1 1 1 0 2 1 0 0 0]]


## `apply same thing on dataset`

In [7]:
data = pd.read_csv('E:\INNO\IMDB Dataset.csv')
data.head()
data = data[:10000]

In [8]:
from sklearn.preprocessing import LabelBinarizer
le = LabelBinarizer()
data['sentiment'] = le.fit_transform(data['sentiment'])

In [9]:
data.head()

review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1

In [10]:
data.shape

(10000, 2)

# `Preprocessing`

In [11]:
data.__len__()

10000

In [12]:
data['sentiment'].value_counts()

1    5028
0    4972
Name: sentiment, dtype: int64

### break down the given tokens, tokenization

In [13]:
words_count = [nltk.word_tokenize(data['review'][i]).__len__() for i in range(len(data['review']))]

In [14]:
print(words_count)

[380, 201, 205, 175, 283, 145, 158, 203, 154, 45, 131, 211, 475, 164, 57, 165, 158, 336, 135, 150, 395, 236, 77, 416, 170, 149, 700, 176, 148, 733, 518, 440, 125, 759, 291, 465, 110, 373, 148, 309, 150, 248, 215, 315, 216, 277, 83, 173, 848, 134, 499, 734, 210, 93, 233, 272, 249, 199, 570, 558, 189, 206, 140, 56, 224, 353, 402, 155, 245, 359, 262, 325, 322, 208, 327, 176, 382, 725, 154, 343, 184, 180, 315, 485, 88, 166, 371, 159, 243, 442, 217, 253, 495, 197, 181, 351, 226, 168, 234, 597, 153, 900, 169, 352, 228, 253, 129, 350, 204, 137, 194, 223, 57, 137, 310, 150, 374, 98, 107, 352, 118, 203, 272, 174, 181, 140, 492, 157, 238, 156, 215, 518, 202, 148, 239, 485, 130, 305, 356, 327, 478, 343, 725, 118, 345, 368, 265, 357, 151, 352, 198, 209, 214, 238, 247, 104, 973, 181, 155, 134, 64, 250, 82, 626, 474, 94, 148, 284, 142, 424, 334, 201, 760, 467, 365, 340, 259, 969, 243, 256, 159, 145, 619, 361, 72, 354, 625, 107, 227, 598, 404, 855, 133, 63, 157, 247, 264, 233, 606, 141, 125, 251, 390

### counting the number of words

In [15]:
words_count.__len__()

10000

### total nmuber of words

In [16]:
sum(words_count)

2793846

### sample review

In [17]:
data['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

In [18]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\manuj\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [19]:
stop_words = set(stopwords.words('english'))
print(stop_words.__len__())
print(stop_words)

179
{'weren', 'myself', "you'd", "wasn't", 'her', 'you', 'down', 'very', 'had', 'are', 'ours', 'no', 'can', 'doing', 'here', "you've", 'being', 'between', 'his', 'what', 'their', 'now', 'that', 'we', 'hadn', 'just', "shan't", 'such', 'my', 'yourselves', 'shan', 'because', 'will', 'other', 'few', 'll', 'there', 'been', 'most', 'same', 'aren', 'am', "hadn't", 'of', "haven't", 'how', 'yourself', 'once', 'at', 'but', 'it', 'on', 'into', 'our', 'against', 'with', 'too', 'again', 'in', 'mustn', "weren't", 'off', 'these', 'wasn', "didn't", 'ourselves', 'itself', 'them', 'until', 'wouldn', 'don', 'i', "it's", 'about', 'won', "isn't", 'below', 'then', 'should', 'this', 'was', 'hers', "couldn't", 'so', 'themselves', "she's", 'some', "needn't", 'an', "don't", 'which', 'those', 'have', 'a', 'm', 'than', "you'll", 'where', 'me', 'both', 'before', 'needn', 'didn', "shouldn't", 'whom', 'having', 'y', 'by', 'doesn', "you're", 'while', "aren't", "won't", 'each', 'through', 'more', 's', "should've", 'th

### remove stopwords
### regex is for http links

In [20]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

In [21]:
def cleaning_review(data):
    all_reviews = list()
    lines = data['review'].values.tolist()
    for i in lines:
        text = i.lower()
        pattern = re.compile('http[s]?://(?:[A-Za-z]|[0-9]|[$-_@,.&*]|[(\)!]|[?:0-9a-fA-F])+')
        text = pattern.sub('',text)
        tokens = nltk.word_tokenize(text)
        table = str.maketrans('','',string.punctuation)
        stripped = [w.translate(table) for w in tokens]
        words = [word for word in stripped if word.isalpha()]
        stop_words = set(stopwords.words('english'))
        stop_words.discard('not')
        words =  [lemmatizer.lemmatize(w,'v') for w in words if not w in stop_words]
        words = ' '.join(words)
        all_reviews.append(words)
    return (all_reviews)

In [22]:
vals = cleaning_review(data)

## `Note: In industry we write code in class`

In [23]:
vals[0]

'one reviewers mention watch oz episode hook right exactly happen br br first thing strike oz brutality unflinching scenes violence set right word go trust not show faint hearted timid show pull punch regard drug sex violence hardcore classic use word br br call oz nickname give oswald maximum security state penitentary focus mainly emerald city experimental section prison cells glass front face inwards privacy not high agenda em city home many aryans muslims gangstas latinos christians italians irish scuffle death star dodgy deal shady agreements never far away br br would say main appeal show due fact go show would nt dare forget pretty picture paint mainstream audiences forget charm forget romance oz nt mess around first episode ever saw strike nasty surreal could nt say ready watch develop taste oz get accustom high level graphic violence not violence injustice crook guard sell nickel inmates kill order get away well mannered middle class inmates turn prison bitch due lack street s

### stopwords are removed
### lemmatization based on verb is done to remove tenses

In [24]:
words_count = [nltk.word_tokenize(vals[i]).__len__() for i in range(len(vals))]

In [25]:
print(sum(words_count))

1233820


### size of tokens decreased by big quantity

In [26]:
vector = CountVectorizer(min_df=3)
# ignore those tokens which appear in less than 3 sentences
x = vector.fit_transform(vals).toarray()
y = data['sentiment'].to_numpy()
print(x.shape)
print(y.shape)

(10000, 19143)
(10000,)


In [27]:
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)

In [29]:
print(f'accuracy: {accuracy_score(y_test,y_pred)}')

accuracy: 0.6265


In [31]:
y_pred[:5]

array([0, 1, 0, 0, 1])

In [32]:
y_test[:5]

array([0, 0, 0, 1, 1])

In [33]:
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(y_pred,y_test)
print(matrix)

[[725 476]
 [271 528]]


In [34]:
X_train[:5]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [35]:
X_train.shape

(8000, 19143)

# `Very important => click the link below`
-----------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------

### [Quick Introduction to Bag-of-Words (BoW) and TF-IDF for Creating Features from Text](https://www.analyticsvidhya.com/blog/2020/02/quick-introduction-bag-of-words-bow-tf-idf/)

------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------

# `END ------------------------------------`